# Generated by Django 5.0.6 on 2024-06-27 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pulse_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='watchlist',
            options={'ordering': ['-created_at']},
        ),
    ]
