# Generated by Django 5.0.6 on 2024-07-18 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pulse_tracker', '0002_alter_watchlist_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='percentage_change',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
