# Generated by Django 5.0.6 on 2024-06-11 06:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0006_userwallet_is_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoTrade',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('trade_type', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=50)),
                ('quantity', models.FloatField()),
                ('target_price', models.FloatField()),
                ('is_executed', models.BooleanField(default=False)),
                ('telegram_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crypto_trade', to='accounts.telegramuser')),
                ('user_wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_wallet', to='accounts.userwallet')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
