# Generated by Django 5.0.6 on 2024-06-21 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0002_remove_cryptotrade_is_executed_cryptotrade_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptotrade',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('failed', 'Failed'), ('in_process', 'In Process')], default='open', max_length=50),
        ),
    ]
