# Generated by Django 5.0.6 on 2024-07-04 12:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0004_Recifi_alter_cryptotrade_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecifiToken',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('token_address', models.CharField(max_length=42)),
                ('Recifi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Recifi_token', to='trade.Recifi')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
