# Generated by Django 5.0.6 on 2024-07-08 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0005_Recifitoken'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='Recifitoken',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='cryptotrade',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('failed', 'Failed'), ('in_process', 'In Process'), ('cancelled', 'Cancelled')], default='open', max_length=50),
        ),
    ]
