# Generated by Django 5.0.6 on 2024-07-16 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0007_alter_Recifi_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='Recifi',
            old_name='percentage_change',
            new_name='pecentage_change_1year',
        ),
        migrations.AddField(
            model_name='Recifi',
            name='pecentage_change_7days',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='Recifi',
            name='percentage_change_24hrs',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='Recifi',
            name='percentage_change_30days',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
