# Generated by Django 5.0.6 on 2024-07-16 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0009_Recifi_price_change_1year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='Recifi',
            name='pecentage_change_1year',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='Recifi',
            name='pecentage_change_7days',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='Recifi',
            name='percentage_change_24hrs',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='Recifi',
            name='percentage_change_30days',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
