# Generated by Django 5.0.6 on 2024-06-05 09:29

from django.db import migrations, models
from utils.encryption import encrypt_text


def encrypt_private_keys(apps, schema_editor):
    UserWallet = apps.get_model("accounts", "UserWallet")

    for wallet in UserWallet.objects.all():
        wallet.private_key = encrypt_text(wallet.private_key)
        wallet.save(update_fields=["private_key"])


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_defaultwallet_deleted_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userwallet",
            name="private_key",
            field=models.CharField(max_length=250),
        ),
        migrations.RunPython(encrypt_private_keys),
    ]
