# Generated by Django 5.0.6 on 2024-06-27 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_userwallet_is_verified'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='defaultwallet',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='telegramuser',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='userwallet',
            options={'ordering': ['-created_at']},
        ),
    ]
