TELEGRAM_USER_MESSAGE = "Telegram user id is required."
DEFAULT_WALLET_MESSAGE = "Default wallet is not configured."
WALLET_NOT_FOUND = "User wallet not found."
WALLET_NOT_BELONG = "This wallet does not belong to you."
WALLET_ADDRESS_REQ = "Wallet address is required."
